version: '1.0'
mode: remote
identifier: AzureCrowRunner
category: Production
username: crowuser
jobs:
- name: CROW CROWFLOW 
  stages:
  - name: Updating Azure Server
    tasks:
      shell:
        enabled: true
        shell: bash
        steps:
        - apt-get update -y
