version: '1.0'
mode: remote
identifier: AzureCrowRunner
category: Production
username: crowuser
jobs:
- name: CROW CROWFLOW 
  stages:
  - name: Updating Azure Server
    tasks:
      shell:
        enabled: true
        shell: bash
        steps:
        - sudo apt-get update -y

  # Install Git iff missing (your helper also attempts this; doing it here makes logs clearer)
  - name: Ensure Git Installed
    tasks:
      shell:
        enabled: true
        shell: bash
        steps:
          - set -euxo pipefail
          - |
            if command -v git >/dev/null 2>&1; then
              echo "git already installed"
            else
              if command -v apt-get >/dev/null 2>&1; then
                DEBIAN_FRONTEND=noninteractive apt-get install -y git ca-certificates
              elif command -v dnf >/dev/null 2>&1; then
                dnf install -y git
              elif command -v yum >/dev/null 2>&1; then
                yum install -y git
              elif command -v apk >/dev/null 2>&1; then
                apk add --no-cache git ca-certificates
              elif command -v zypper >/dev/null 2>&1; then
                zypper --non-interactive install -y git
              else
                echo "Could not install git automatically" >&2
                exit 1
              fi
            fi
          - git --version