version: '1.0'
mode: remote
identifier: AzureCrowRunner
category: Production
username: crowuser
environment:
  # === Crowstore-backed values ===
  CLONE_DIR:    { value: crowstore://clonedir }
  SOURCE_URL:   { value: crowstore://sourceurl }
  GIT_PROVIDER: { value: crowstore://gitprovider }
  GIT_USERNAME: { value: crowstore://gitusername }
  GIT_TOKEN:    { value: crowstore://gittoken }
  DOCKERFILE_PATH:    { value: crowstore://dockerfile}

  # Either use a literal branch…
  #BRANCHES:     { value: "main" }

  # BRANCHES:   { value: crowstore://gitbranch }

  # === Matching Crowstore tokens (CROWSTORE_TOKEN_<CREDNAME UPPERCASED>) ===
  # These must match the *names after* crowstore:// exactly (uppercased, no extra underscores).
  CROWSTORE_TOKEN_CLONEDIR:    { value: 379c89bdfbe33b78a65f24056d30ea5e }
  CROWSTORE_TOKEN_SOURCEURL:   { value: 75d5d957b968d54a85d048c091612963 }
  CROWSTORE_TOKEN_GITPROVIDER: { value: fe251dd97eccb2ea55da1072ca09c4b8 }
  CROWSTORE_TOKEN_GITUSERNAME: { value: c9e081c08366187bb1ab52a1185696f8 }
  CROWSTORE_TOKEN_GITTOKEN:    { value: 06638103869c385bdb0850f4c248ca3b }
  CROWSTORE_TOKEN_DOCKERFILE:    { value: 94bffbb39aec840c9dd2c80dcd150701 }

  # Only needed if you use crowstore://gitbranch above:
  #CROWSTORE_TOKEN_GITBRANCH: { value: f4e9076b9dc189ad06dfc485fd731bf7 }
jobs:
- name: CROW CROWFLOW 
  stages:
  - name: Updating Azure Server
    tasks:
      shell:
        enabled: false
        shell: bash
        steps:
        - sudo apt-get update -y

  # Install Git iff missing (your helper also attempts this; doing it here makes logs clearer)
  - name: Install GIT Python(Debian)
    tasks:
      packages:
        enabled: false
        # Keep this list focused on universally-available kits to avoid repo conflicts
        kits:
          - python            # python3, pip, venv
          - git-lfs
        extra_os_packages:
          - shellcheck        # linter that’s reliably in Ubuntu/Debian/Alpine repos
  
        update_cache: true
        verbose: true
        fail_fast: true
        pm_timeout_s: 600
        pm_retries: 3

  # ======== Core: Checkout (invokes your Python helper under the hood) ========
  - name: Git Checkout one
    tasks:
      checkout:
        enabled: false
        private_repo: true
        # --- required / important fields your function expects ---
        clone_dir: env=CLONE_DIR
        source_url: env=SOURCE_URL
        branches: 
        - master
        provider: env=GIT_PROVIDER
        username: env=GIT_USERNAME
        token: env=GIT_TOKEN

  - name: Trivy FS (source workspace)
    tasks:
      trivy:
        enabled: false
        debug: true                 # set true to enable --debug + verbose logs
        working_directory: /tmp/crow
        cache_dir: /home/crowuser/.cache/trivy
        format: json                 # table|json|sarif|cyclonedx|spdx-json
        output_dir: /tmp/crow/reports
        timestamp_output: true
        fail_fast: true
        retries: 1
        retry_delay: 3
        timeout: "10m"
        skip_update: false
        severity: "CRITICAL,HIGH,MEDIUM"
        ignore_unfixed: true
        scanners: "vuln,secret,config"
        list_all_pkgs: false
        skip_dirs: [".git"]      
        skip_files: []
        targets:
          - "fs ."         

  - name: Convert Reports
    tasks:
      file_converter:
        enabled: false
        inputs:
          - /tmp/crow/reports/filesystem-.-20250829-062515.json
        output_dir: /tmp/crow/converted
        formats: [md]     # any subset: md | txt | html
        max_items: 100
        include_pretty: true         # also writes *.pretty.json when input is JSON
        title_prefix: "CI Report"            
  - name: Email Report (Model)
    tasks:
      email:
        enabled: false
        ensure_install: false
        to: ["mohamed.sesay@outlook.com.au"]
        subject: "Trivy Summary for Crow"
        template_path: "/tmp/crow/converted/filesystem-.-20250829-062515-summary.md"
        context:
          name: "Prod Runner"
        attachments:
          - "/tmp/crow/reports/filesystem-.-20250829-062515.json"
          - "/tmp/crow/converted/filesystem-.-20250829-062515-summary.md"
        track_open: true
        report: true
        priority: high
        # schedule: "2025-07-01 09:00"   # (optional)
        secret_source: env
        smtp:
          host: "smtp.gmail.com"
          port: 587
          username: "alhajibangs@gmail.com"
          password: "ufhp vqie rgdy cadh"
          from_email: "alhajibangs@gmail.com"
          reply_to: "alhajibangs@gmail.com"
          use_tls: true        

  - name: Image Build Stage
    tasks:
      docker_build:
        enabled: true
        image_name: devopsbot.azurecr.io/crow-cli
        build_tag: V0.1.31
        dockerfile_path: env=DOCKERFILE_PATH      