version: '1.0'
mode: remote
identifier: AzureCrowRunner
category: Production
username: crowuser
jobs:
- name: CROW CROWFLOW 
  stages:
  - name: Updating Azure Server
    tasks:
      shell:
        enabled: true
        shell: bash
        steps:
        - sudo apt-get update -y

  # Install Git iff missing (your helper also attempts this; doing it here makes logs clearer)
  - name: Install GIT Python(Debian)
    tasks:
      packages:
        enabled: true
        # Keep this list focused on universally-available kits to avoid repo conflicts
        kits:
          - python            # python3, pip, venv
          - git-lfs
        extra_os_packages:
          - shellcheck        # linter that’s reliably in Ubuntu/Debian/Alpine repos
  
        update_cache: true
        verbose: true
        fail_fast: true
        pm_timeout_s: 600
        pm_retries: 3

          