version: '1.0'
mode: remote
identifier: AzureCrowRunner
category: Production
username: crowuser

environment:
  # === Crowstore-backed values (names after crowstore:// MUST match token suffixes) ===
  CLONE_DIR:
    value: crowstore://clone_dir
  SOURCE_URL:
    value: crowstore://source_url
  GIT_PROVIDER:
    value: crowstore://git_provider
  GIT_USERNAME:
    value: crowstore://git_username
  GIT_TOKEN:
    value: crowstore://git_token
  BRANCHES:
    value: crowstore://branches

  # === Matching tokens (CROWSTORE_TOKEN_<UPPERCASE OF name after crowstore://>) ===
  CROWSTORE_TOKEN_CLONE_DIR:
    value: 379c89bdfbe33b78a65f24056d30ea5e
  CROWSTORE_TOKEN_SOURCE_URL:
    value: 75d5d957b968d54a85d048c091612963
  CROWSTORE_TOKEN_GIT_PROVIDER:
    value: fe251dd97eccb2ea55da1072ca09c4b8
  CROWSTORE_TOKEN_GIT_USERNAME:
    value: c9e081c08366187bb1ab52a1185696f8
  CROWSTORE_TOKEN_GIT_TOKEN:
    value: 06638103869c385bdb0850f4c248ca3b
  CROWSTORE_TOKEN_BRANCHES:
    value: f4e9076b9dc189ad06dfc485fd731bf7

jobs:
- name: CROW CROWFLOW
  stages:
  - name: Updating Azure Server
    tasks:
      shell:
        enabled: true
        shell: bash
        steps:
        - sudo apt-get update -y

  - name: Install GIT Python(Debian)
    tasks:
      packages:
        enabled: true
        kits:
          - python
          - git-lfs
        extra_os_packages:
          - shellcheck
        update_cache: true
        verbose: true
        fail_fast: true
        pm_timeout_s: 600
        pm_retries: 3

  - name: Git Checkout
    tasks:
      checkout:
        enabled: true
        clone_dir: env=CLONE_DIR
        source_url: env=SOURCE_URL
        branches: env=BRANCHES
        provider: env=GIT_PROVIDER
        username: env=GIT_USERNAME
        token: env=GIT_TOKEN

       