version: '1.0'
mode: remote
identifier: AzureCrowRunner
category: Production
username: crowuser
jobs:
- name: CROW CROWFLOW 
  stages:
  - name: Updating Azure Server
    tasks:
      shell:
        enabled: true
        shell: bash
        steps:
        - sudo apt-get update -y

  # Install Git iff missing (your helper also attempts this; doing it here makes logs clearer)
  - name: Install GIT (Debian)
    tasks:
      package_management:
        enabled: false
        steps:
        - type: apt
          names:
          - ca-certificates
          - git
          state: present
          update_cache: true
          retries: 4
          retry_delay: 5